Login page errors improvments
rubyforgood/babywearing pull request #176
Opened 2019-10-23 17:05 UTC by ahmedash95

Resolves #169

### Description
Regarding #169, this PR improves errors at Login page. because we are using a shared component I think the place of the error right now is good enough for the user to notice and knows there is something wrong with his login credentials

### Type of change
* New feature (non-breaking change which adds functionality)

### Checklist
- [x] Change text from "Invalid Email or password" to "Invalid Email/Password"
- [x] Error text should be red (color value is up to your discretion, should be vivid on the background)
- [ ] Increase error text size by ~25%
- [x] Position the error text to be directly above the Log In component (see screenshot) 
### How Has This Been Tested?
Try to login with invalid credentials 

### Screenshots
![image](https://user-images.githubusercontent.com/8272048/67416681-8890d180-f5c7-11e9-9bad-cf0ebe9f297a.png)

2019-10-23 17:54 UTC, abronkema requested changes

2019-10-23 17:54 UTC, abronkema commented on config/locales/devise.en.yml
> +      invalid: "Invalid %{authentication_keys}/password."
Could you update the casing of `password` to read `Password` for consistency? 

Otherwise, this looks great. Thanks for the quick change!

2019-10-23 17:55 UTC, ahmedash95 commented on config/locales/devise.en.yml
> +      invalid: "Invalid %{authentication_keys}/password."
Resolved. and my pleasure the project is really cool

2019-10-24 00:22 UTC, pollygee approved these changes

2019-10-24 00:23 UTC, merged