171 week advance reminder email
rubyforgood/babywearing pull request #191
Opened 2019-10-31 14:30 UTC by NiquiCara

Ref #171 

Creates mailer for when carrier is due in a week. Tested with 
```
2.6.3 :004 > ReminderMailer.week_advance_notice_email(User.first, "Bloop", "Farts", "Banananananas")
  User Load (0.4ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
  Rendering reminder_mailer/week_advance_notice_email.html.erb within layouts/mailer
  Rendered reminder_mailer/week_advance_notice_email.html.erb within layouts/mailer (0.5ms)
ReminderMailer#week_advance_notice_email: processed outbound mail in 15.5ms
 => #<Mail::Message:47130221780160, Multipart: false, Headers: <From: from@example.com>, <To: email@example.com>, <Subject: Baby Carrier Due For Return>, <Mime-Version: 1.0>, <Content-Type: text/html>>
```

**merge after #189**

2019-11-01 07:51 UTC, dixpac approved these changes

2019-11-01 07:51 UTC, dixpac commented on app/mailers/reminder_mailer.rb
> +    @first_name = user.full_name
We don't need this ivar, we can use `@user` ivar to access `full_name` directly in the mailer template

2019-11-01 07:53 UTC, dixpac requested changes
Thanks! Looks good just one tinny comment

2019-11-02 12:26 UTC, pollygee commented
@NiquiCara one last time we have that merge conflict, can you please resolve so we can merge this last one?  Thanks!

2019-11-02 13:04 UTC, merged

2019-11-02 13:05 UTC, dixpac commented
@NiquiCara  @pollygee  and I resolved conflicts. Thanks so much for your help, keep it coming :)