Remove responding to json from controllers
rubyforgood/babywearing pull request #207
Opened 2019-11-04 19:15 UTC by m-pereira

Resolves https://github.com/rubyforgood/babywearing/issues/206

### Description
This PR is just removing the json responding from controllers.

2019-11-04 19:24 UTC, m-pereira commented on app/controllers/categories_controller.rb
> +    if @category.destroy
Can it be ignored?

2019-11-05 01:28 UTC, DamirSvrtan commented on app/controllers/categories_controller.rb
> +    if @category.destroy
I'll check it out, I agree, this currently reads better!

2019-11-05 06:57 UTC, DamirSvrtan requested changes
Hey @m-pereira, thanks for another contribution! 🎉 Can you please add that rubocop line and as well simplify  the [signed agreements controller](https://github.com/rubyforgood/babywearing/blob/master/app/controllers/signed_agreements_controller.rb#L13) (remove the respond_to).

2019-11-05 06:57 UTC, DamirSvrtan commented on app/controllers/categories_controller.rb
> +    if @category.destroy
Hi @m-pereira, can you put this line in the .rubocop.yml file:

```
Style/IfUnlessModifier:
  Enabled: false
```

(right below Rails enabled true).

2019-11-05 13:04 UTC, m-pereira commented on app/controllers/categories_controller.rb
> +    if @category.destroy
It's added

2019-11-05 13:06 UTC, m-pereira commented
@DamirSvrtan I saw that there are many rubocop offenses, I'm going to add a new PR to fix that!

2019-11-06 06:49 UTC, DamirSvrtan commented
This is great @m-pereira, thanks for a great contribution! 🎉

2019-11-06 06:49 UTC, merged